/* @flow */
export const LOAD_EXERCISE = 'LOAD_EXERCISE';
export const SAVE_EXERCISE = 'SAVE_EXERCISE';
export const SAVE_EXERCISE_SUCCESS = 'SAVE_EXERCISE_SUCCESS';
export const SAVE_EXERCISE_FAILURE = 'SAVE_EXERCISE_FAILURE';
export const UPDATE_EXERCISE_METADATA = 'UPDATE_EXERCISE_METADATA';
