// flow-typed signature: 2b0e305e803194c4f0d80736428dc3eb
// flow-typed version: <<STUB>>/remarkable-react_v^0.2.0/flow_v0.49.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remarkable-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remarkable-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remarkable-react/lib/index' {
  declare module.exports: any;
}

declare module 'remarkable-react/lib/lib/renderer' {
  declare module.exports: any;
}

declare module 'remarkable-react/lib/lib/token-tree-builder' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remarkable-react/lib/index.js' {
  declare module.exports: $Exports<'remarkable-react/lib/index'>;
}
declare module 'remarkable-react/lib/lib/renderer.js' {
  declare module.exports: $Exports<'remarkable-react/lib/lib/renderer'>;
}
declare module 'remarkable-react/lib/lib/token-tree-builder.js' {
  declare module.exports: $Exports<'remarkable-react/lib/lib/token-tree-builder'>;
}
