/* @flow */
export const LOAD_EXERCISE = 'LOAD_EXERCISE';
export const LOAD_EXERCISE_SUCCESS = 'LOAD_EXERCISE_SUCCESS';
export const LOAD_EXERCISE_FAILURE = 'LOAD_EXERCISE_FAILURE';
export const START_EXERCISE = 'START_EXERCISE';
export const ANSWER_QUESTION = 'ANSWER_QUESTION';
export const VALIDATE_ANSWER = 'VALIDATE_ANSWER';
export const NEXT_QUESTION = 'NEXT_QUESTION';